### ISSUE TITLE
[Question] Why is the first `reset()` of `performance_benchmark()` not counted in the runtime.

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/PettingZoo#1007]
### Question

https://github.com/Farama-Foundation/PettingZoo/blob/969c079164e6fd84b4878f26debfeff644aa2786/pettingzoo/test/performance_benchmark.py#L7-L13

```py
     env.reset()  # not counted as part of the profile
     start = time.time() # this after the first reset()
```

**Comment by elliottower** [comment]
Good catch, I'm looking into the way gymnasium does it and it seems that env.reset() is called inside of the loop rather than before it ([link](https://github.com/Farama-Foundation/Gymnasium/blob/79899888e445d873ddae97973693830fb5dde734/gymnasium/utils/performance.py#L64)), so I think we should change it to match. Resetting can sometimes take a large amount of time, and is good to measure as well. Would you be willing to submit a PR fixing this? Otherwise I can do it myself

**Comment by Kallinteris-Andreas** [comment]
Hey, (note: I wrote the `perfomance.py` in gym)

1) that link you have posted of `perfomance_init()` which measures the initialization performance

2) from my testing the current implementation makes sense because some environments do not fully initialize until after the first `reset()` (see `mujoco` with `render_mode=`rgb_array` for example)
