### ISSUE TITLE
[Question] Simple Spread v3 different reward of the agents

### ISSUE THREAD

**Issue by Mytolo** [Farama-Foundation/PettingZoo#1021]
### Question
The rewards for the multi particle environment simple_sread are supposed to be the same for every time steps. However, the are for some timesteps different, which can be seen in this issue. 

**Reproduction of the Issue:**

```python

e = pettingzoo.mpe.simple_spread_v3.env()

e.reset(seed=123)

actions = np.array([[3, 1, 4, 2, 0, 1, 0, 1, 1, 1, 1, 4],
       [0, 0, 1, 3, 4, 3, 2, 2, 4, 2, 0, 4],
       [0, 2, 3, 2, 0, 1, 3, 3, 2, 0, 3, 0]])

In [..]: for a1,a2,a3 in zip(actions[0,:], actions[1,:], actions[2,:]):
    ...:     e.step(a1)
    ...:     e.step(a2)
    ...:     e.step(a3)
    ...:     print(e.rewards)
    ...:
{'agent_0': -1.232097444068718, 'agent_1': -1.232097444068718, 'agent_2': -1.232097444068718}
{'agent_0': -1.268766325864818, 'agent_1': -1.268766325864818, 'agent_2': -1.268766325864818}
{'agent_0': -1.2759707697215021, 'agent_1': -1.2759707697215021, 'agent_2': -1.2759707697215021}
{'agent_0': -1.2482396223642986, 'agent_1': -1.2482396223642986, 'agent_2': -1.2482396223642986}
{'agent_0': -1.1983912997060198, 'agent_1': -1.1983912997060198, 'agent_2': -1.1983912997060198}
{'agent_0': -1.1622829338032408, 'agent_1': -1.1622829338032408, 'agent_2': -1.1622829338032408}
{'agent_0': -1.1649412216478077, 'agent_1': -1.1649412216478077, 'agent_2': -1.1649412216478077}
{'agent_0': -1.1753803258928228, 'agent_1': -1.1753803258928228, 'agent_2': -1.1753803258928228}
{'agent_0': -1.2043056728563828, 'agent_1': -1.2043056728563828, 'agent_2': -1.2043056728563828}
{'agent_0': -1.226673569892578, 'agent_1': -1.226673569892578, 'agent_2': -1.226673569892578}
{'agent_0': -1.2808258629517757, 'agent_1': -1.2808258629517757, 'agent_2': -1.2808258629517757}
{'agent_0': -1.876276275263453, 'agent_1': -1.876276275263453, 'agent_2': -1.376276275263453}
```

As it can also be seen in the below picture, the rewards at the last step are different. For different seeds, this occurs at different time steps. Might this depend on Python 3.11? Or is there another reason for this?
Thanks for Clarification.

<img width="680" alt="image" src="https://github.com/Farama-Foundation/PettingZoo/assets/17086993/d8d67a47-622b-4725-ad0d-48a00bf6905f">

**Comment by Mytolo** [comment]
For the first 10 Episodes with a random sampler with seed 123: 
![MPE_SIMPLE_SPREAD_SEED123](https://github.com/Farama-Foundation/PettingZoo/assets/17086993/5ffcc744-f035-440b-a6cb-9e1e4687e42e)
Left: Episode total reward, Right: step based reward

**Comment by Mytolo** [comment]
Also tested with seeds 231, 314, 2312, 3333 occur in 25 Episodes at least three times:

**MIsses**
123     [86, 87, 88, 89, 289, 611, 612, 613]
231     [93, 94, 95, 96, 97, 187, 260, 261, 283, 284, 313, 314]
314     [411, 412, 417, 418, 419, 423, 424]
2312    [222, 374, 375]
3333    [139, 140, 174, 175, 211, 212, 213, 214, 215, 291, 324, 325]

For debugging i can also provide the suitable actions. Is this supposed to be that way?

**Comment by elliottower** [comment]
Are any other MPE environments like this? And where did you get that it’s supposed to be the same reward? I’m not personally very familiar with them so it’s hard to diagnose the problem but definitely happy to look over a PR or create one if you can locate where in the code it should be changed. 

We are in the process of creating MPE2 which moves these envs out of pettingzoo and fixes some bugs and such. If you’d like to help with that we would love some more hands (there will be a paper from it so it could be a good research opportunity as well)

**Comment by SinergAIze** [comment]
Hi!

I could be way off track here, but I believe Simple Spread is meant to have different reward values for each agent at each time-step depending on collisions, based on the value of the `local_ratio` parameter that you initialise the environment with in the `e = pettingzoo.mpe.simple_spread_v3.env()`. You can pass `local_ratio=...` as a keyword argument there. 

The `local_ratio` parameter specifies how much each agent's 'individual' reward should be weighted, compared to how the 'global reward' (same for all agents) should be weighted. The reward assigned to each agent is based on a weighted average between the global and individual reward, as shown in [on this line](https://github.com/Farama-Foundation/PettingZoo/blob/97c4a5d13264ec7f3a44492a569d5efd370b30cd/pettingzoo/mpe/_mpe_utils/simple_env.py#L189). 

In Simple Spread's case, individual reward is assigned based on collisions between agents, while global reward, which is assigned equally for all agents, corresponds to the sum of the distance between each landmark and the closest agent to that landmark.

If this is the problem, by overwriting the default `local_ratio` value of 0.5 with `e = pettingzoo.mpe.simple_spread_v3.env(local_ratio=0)`, you should get the same rewards for all agents. HOWEVER: Since you won't be assigning any reward (punishment) based on collisions, the agents will have no incentive to learn to avoid colliding.

All the logic for the above is specified in the [`.reward()`](https://github.com/Farama-Foundation/PettingZoo/blob/97c4a5d13264ec7f3a44492a569d5efd370b30cd/pettingzoo/mpe/simple_spread/simple_spread.py#L167) and [`.global_reward()`](https://github.com/Farama-Foundation/PettingZoo/blob/97c4a5d13264ec7f3a44492a569d5efd370b30cd/pettingzoo/mpe/simple_spread/simple_spread.py#L175C3-L175C3) Simple Spread `Scenario` methods.

I hypothesise that at that last step in your example `agent_0` and `agent_1` are in a collision with each other, and therefore both get an extra 0.5 * -1 = -0.5 reward each. So while the global reward obtained by all agents is of -1.376276275263453, `agent_0` and `agent_1` are also penalised for colliding, but individually.

Hope this helps!

**Comment by Mytolo** [comment]
Sure it helps! I thought of this as well. Somehow it was unclear to me that the rewards are different, because I thought collision is in general reward discounting. But thanks for clarification. I do not have to worry any more!
