### ISSUE TITLE
[Bug Report] Landmarks and Goals Move During Episode in MPE Environment

### ISSUE THREAD

**Issue by violetxi** [Farama-Foundation/PettingZoo#1043]
### Describe the bug

Hello,

I have encountered an issue with the simple_spread environment in the PettingZoo library, where landmarks and goals appear to move during an episode in the rendered output. According to the environment's design, these entities should be static and their positions should only change between episodes (i.e., after a call to env.reset()), not within an episode.

Here are the steps to reproduce the issue:

### Code example

```shell
from pettingzoo.mpe import simple_spread_v3
import matplotlib.pyplot as plt
import cv2

# Initialize the environment
env = simple_spread_v3.parallel_env(N=3, render_mode='rgb_array')

# Reset the environment
env.reset()

# Initialize video writer
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
video = cv2.VideoWriter('test.mp4', fourcc, 30, (700, 700))

for _ in range(100):
    # Choose random actions for each agent
    actions = {agent: env.action_spaces[agent].sample() for agent in env.agents}    
    # Step the environment
    env.step(actions)
    
    # Render the environment
    frame = env.render()
    
    # Convert frame to BGR (for VideoWriter)
    # frame_bgr = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    
    # Write the frame to the video file
    video.write(frame)

# Close the video writer
video.release()

# Close the environment
env.close()
```

### System info

Python: 3.9.17
pettingzoo version: 1.23.1
Operating system name: Linux
Operating system release: 5.4.0-91-generic
Operating system version: #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by SinergAIze** [comment]
Hi!

I can't be sure this applies, but I think it's worth mentioning that the rendering in all MPE environments is designed to keep all agents in the frame at all times. This implies that if an agent moves outside of the initial rendered window, the rendering function will automatically zoom out to keep all agents in the field of view. As a consequence, this will also affect the landmarks: While zooming out, the landmarks will appear to be moving towards the center, this is in fact just a perception: Due to the movement of the frame of reference, each landmark is also 'moving', in reality though, if you print out each landmarks' `x` and `y` position (you can easily do this in your loop via `print([l.state.p_pos for l in env.unwrapped.world.landmarks])`), you'll see that their values are not changing. (I hope! 😄)

I hope this helps!

**Comment by elliottower** [comment]
Hi @violetxi, does the comment above solve your issue? I don't have much knowledge on the MPE environments unfortunately but I can try to find someone who does if your question is still open
