### ISSUE TITLE
[Question] Code missing in PettingZoo documentation site

### ISSUE THREAD

**Issue by labanca** [Farama-Foundation/PettingZoo#1106]
### Code missing in PettingZoo documentation site

It seems that the tutorial code on the official website is not showing: https://pettingzoo.farama.org/tutorials/custom_environment/2-environment-logic/#code

I tried different browsers and nothing is showed either way. So, as I trying to do the tutorials, the missing code was a bit underwhelming :(

**Comment by elliottower** [comment]
Oops, sorry about this. You need to go on the master branch, as we have fixed this but haven't pushed a new release patch fixing it yet. 

https://pettingzoo.farama.org/main/tutorials/custom_environment/2-environment-logic/#code (bottom right corner says `main (unstable)` instead of 1.24.1)

I'll close this when we do make the release

**Comment by labanca** [comment]
Thanks for the help!
