### ISSUE TITLE
[Question] Custom environment with complex observation_space

### ISSUE THREAD

**Issue by wklausing** [Farama-Foundation/PettingZoo#1111]
### Question

Hello there, 

I am trying to build a custom environment with an observation_space and observation which is basically a dictionary with lists and single values inside. However, I cannot get the api_test running through. Either observation['observation'].dtype will through an error, because its not a numpy object, or, when observation is a numpy object, space.contains(observation) is false. 

Within api_test.py the test happens between 383-395.

I created an example file called playground.py of this, because the code of my environment is messy. [https://github.com/wklausing/PettingZoo/blob/observation_space_problem/playground.py](url)

Appreciate if someone could take a look. I'm not sure if I've made an error or if there's a bug in the code. 

Regards

**Comment by elliottower** [comment]
Looked at your code and it looks like the problem is just double nested dictionary observations. Since the top level is just an observation with no action mask though maybe you can just delete that and simplify things? 

But we should change the style check to first check that it is a numpy object. And should check if “observation” in observation (the key exists) as well. If you’d like to do a pr fixing this that would be great, otherwise one of us can but it may not be for a little bit as I am busy currently.

**Comment by elliottower** [comment]
Looking back at the API tests we have some warnings that `Observation is not a NumPy array`, but we have a lot of things which assume observations are numpy arrays so there isn't really an easy way to support these kinds of nested observations without changing a lot of how the tests work. If this is still an issue for you let me know, but I think this is so niche a case that you should probably just verify the environment yourself, don't really have the bandwidth to add this new feature set.
