### ISSUE TITLE
[Question] Action Space of MPE Simple Spread.

### ISSUE THREAD

**Issue by ikalemmon** [Farama-Foundation/PettingZoo#1115]
### Question

Hi, 
I want to use MPE "Simple_Spread_v3", for the continuous action space.
In document, action space was showed 

> Action Values : Discrete(5)/Box(0.0, 1.0, (5))
> Agent action space: [no_action, move_left, move_right, move_down, move_up]
> 

I know in discrete setting, action space should be 5 dim.
But in continuous, what does it means? I think it is adequate to use 4dim to represent move in continuous space.

**Comment by elliottower** [comment]
Box(0.0, 1.0, (5)) means an action space comprised of five floating point values. I’d have to check the base scenario MPE code to be 100% sure but I believe it means instead of an integer 1 to move left fully you could have a float array [0, 0.5, 0, 0, 0.5] to move diagonally both to the left and up. The magnitude may be possible to be larger than one as well, to move faster, but I’m not 100% sure. You could do some debugging and print the position came with a value of 1 and a value of 10 for the move left entry to see if it changes anything.

**Comment by elliottower** [comment]
AFAIK though it’s generally easier to train on a discrete action space so you most likely want to keep it default. @murtazarang may be able to help as well.

**Comment by elliottower** [comment]
Feel free to reopen if you have any more questions, just going through and closing issues that have been answered for house keeping
