### ISSUE TITLE
[Proposal] Depend on OpenSpiel for Classic environment internals

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#480]
OpenSpiels implementations of classic environments are all written in C and are dramatically faster than hours (and in some cases are better tested). They also have C implementations of most PettingZoo's classic environments. We would accordingly like to replace these with OpenSpiels over time.

**Comment by elliottower** [comment]
My take on this is that the reference Python envs are very useful to have for people who are making their own custom envs or want to better understand how a game works, but for performance reasons it would be nice to have simple ways to load the openspiel versions as backend. My thinking is a compromise would be to have an input arg that specifies the backend, or a separate environment version like chess_v6 and chess_openspiel_v6. 

One problem is that then it may be difficult to compare results due to differences in implementation. We could definitely use them as a reference for our own testing, like do a seed test type setup to see if the openspiel version of a given game works exactly the same as our version.

**Comment by elliottower** [comment]
Another problem with switching all of our classic environments to use OpenSpiel would be that then PettingZoo as a package always depends on Shimmy. If we end up moving all of the environments into another package then maybe that would be okay, but until then it doesn't make sense.
