### ISSUE TITLE
Ray and PettingZoo compatibility 

### ISSUE THREAD

**Issue by Ascrypto** [Farama-Foundation/PettingZoo#538]
I am working on an environment that relies heavily on Ray 0.8.5, which is incompatible with PettingZoo. Upgrading Ray to 1.8 does solve the compatibility issue but causes problems with the environment (removes ray utilities that are needed for my experiments). My question is: is there a way to work around this issue without upgrading Ray?  Any suggestion would be appreciated.

**Comment by benblack769** [comment]
So while we do not have official support for old versions of ray, I belive you can find a workaround. Pettingzoo interfaces with ray through the PettingZooEnv and ParallelPettingZooEnv wrappers. While the pettingzoo api has changed since ray released 0.8.5, which is why those old wrappers do not work, ray's MultiAgentEnv is unchanged. So, if you copy a new version of this wrapper locally into your codebase, then you should find that old versions of ray will still work with this new wrapper. 

So I would just copy the msot recent version of the wrapper into your code and use it, instead of the out of date wrapper built into ray 0.8.5 https://github.com/benblack769/ray/blob/pettingzoo_upgrade2/rllib/env/wrappers/pettingzoo_env.py

Let us know if you have any more questions.
