### ISSUE TITLE
AttributeError: module 'supersuit' has no attribute 'pettingzoo_env_to_vec_env_v0'

### ISSUE THREAD

**Issue by aduyinuo** [Farama-Foundation/PettingZoo#543]
<img width="1142" alt="Screen Shot 2021-11-19 at 3 01 38 PM" src="https://user-images.githubusercontent.com/40970294/142684608-52fcb6d9-8f72-464d-b08c-fc2dcb2634ce.png">

As shown in the screen shot, I'm trying to run the code scripet in 13-lines tutorial. Are there any changes on `pettingzoo_env_to_vec_env_v0` recently?

**Comment by benblack769** [comment]
Yes, there was an update, and the version was bumped to `pettingzoo_env_to_vec_env_v1`. I guess we should have a deprecation message. Thanks for bringing this up.

**Comment by nikhilweee** [comment]
@jkterry1 I faced the same issue because the [13lines](https://github.com/Farama-Foundation/PettingZoo/blob/968b492b250a935f9a43e9a3f110bc8de280a4cc/tutorials/13_lines.py) tutorial still refers to `pettingzoo_env_to_vec_env_v0`. I'm wondering why this issue was closed? Shouldn't the tutorial be updated as well?

**Comment by nikhilweee** [comment]
I just noticed `concat_vec_envs_v0` also throws an error. (`concat_vec_envs_v1` works though). Maybe this should also be updated in the tutorial.

**Comment by benblack769** [comment]
A new version of supersuit was released a few minutes ago which has an informative error message which tells you what to do. Hopefully this will mitigate this problem until it can be fixed fully.
