### ISSUE TITLE
More Concerns about Pursuit reward

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#583]
My concern can be most easily illustrated by two gifs:

This rollout got 84
![0_3_84](https://user-images.githubusercontent.com/19422700/145899414-430e70b1-2c5d-4d98-9015-cfb434292ebd.gif)

This rollout got 82
![0_2_82](https://user-images.githubusercontent.com/19422700/145899435-09beaf74-d5b4-4755-9ee7-b6b2b3679fa1.gif)

The 84 rollout seems to be /massively/ better than the 82 by visual inspection?

**Comment by RedTachyon** [comment]
The gifs are pretty long so hard to analyze without controls - did the 82 episode terminate?

In any case, it might be due to the thing we discussed about each agent getting its "copy" of the reward. It seems like in the 82 episode, all 8 agents move together, whereas in the 84 episode, they split into two packs. The reward structure actually encourages the former behavior with reward sharing enabled, since 8 agents capturing an evader gives double the reward of 4 agents capturing an evader. So there's a balance between that, episode duration, discounting and how many evaders actually get captured.
