### ISSUE TITLE
Use of PettingZoo environment in my research paper

### ISSUE THREAD

**Issue by AdityaKapoor74** [Farama-Foundation/PettingZoo#585]
Hello community! 
First of all, a wonderful job on building these gym environments for MARL. It has been needed for quite some time now.
Cutting back to the chase, I have been wanting to use multiple PettingZoo environments in my research but I am facing a few issues.
1) In the pursuit env, I am unable to import pursuit_v4, how do I go about that?
2) Is there any way in which I can get local rewards or individual rewards for every agent? 
3) What is the difference between the versions? Have y'all changed the reward formulation, observation formulation, etc?
4) In general, does it take pursuers 500 timesteps to capture all the evaders? Or is it just some arbitrary timestep value?

**Comment by AdityaKapoor74** [comment]
Also, can we enable full observability of the environment? Can someone point me to the docs that will allow me to do that?
Thanks!

**Comment by benblack769** [comment]
1. If you are on the latest release of PettingZoo and you cannot do `from pettingzoo.sisl import pursuit_v4`, then I would try running the equivalent `import pettingzoo.sisl.pursuit_v4 as pursuit_v4`. This is a known problem (but a mysterious one that only certain users at certain times) that we have been unable to track down and fix.
2. Yes, you can access the env.rewards for the AEC environment, which provides the rewards each agent receives at every step. Note that the reward returned from last() is the cumulative reward since an agent's last step, so it may not correspond directly to the entry in the reward's dictionary.
3. You can see the difference in the versions at the bottom of the page in the documentation: https://www.pettingzoo.ml/sisl/pursuit#version-history
4. 500 timesteps is the default value of the `max_cycles` argument, which terminates the environment if it has not ended in 500 steps. You can change the value of this argument with `pursuit_v4.env(max_cycles=10000)` Note that environment termination logic is going to change soon to make it clear why an environment ended.
5. Many pettingzoo environments support a `env.state()` method (of the type described by `env.state_space`), which provides a global view of the environment, meant to be used by a centralized training/decentralized execution method. This method is supported by the butterfly, MPE, MAgent environments. However, it is not yet supported in pursuit.

**Comment by AdityaKapoor74** [comment]
@benblack769 thanks for getting back quickly
Regarding point 2, I shifted from the regular env initialization to parallel_env initialization so I am guessing I will be receiving rewards in the dictionary pertaining to a specific agent only?
Regarding point 4, how close are you to changing the termination logic, is it in the next few days, weeks, months?

Is there any way in which I can ask for stacked frames instead of individual frames in a particular timestep for each agent? If so, can you point me to that as well?

The issue with Pursuit seems to be that as one does not have access to the global state, it becomes a little tough for the AC methods to learn as, in the local FOV of every pursuer, there may or may not be another pursuer and hence it gets difficult to make them to cooperate with one another.

**Comment by benblack769** [comment]
2. Yes, the dictionary is with single-agent rewards only. You can see details here: https://www.pettingzoo.ml/sisl/pursuit. If you want to, you can create a global reward by averaging the local rewards via a wrapper. 
4. Months. 

You can use `supersuit.frame_stack_v1(env)` to change the environment to one where the observation contains stacked frames.

Yes, we are aware that it is challenging. If you wish to make a PR to include a global state() method for pursuit, then we would accept it for sure. Note than an  interesting alternative is to simply share rewards, as in [VDN](https://arxiv.org/abs/1706.05296), which has suprisingly good performance (see [here](https://arxiv.org/pdf/2102.03479.pdf))

**Comment by jkterry1** [comment]
Hey, let us know if you need anything else

**Comment by AdityaKapoor74** [comment]
Thank you, guys!

**Comment by AdityaKapoor74** [comment]
Hey, are there any benchmarks for pursuit_v4? 
What is the reward function like?
I am a little confused here.. @jkterry1 @benblack769

**Comment by jkterry1** [comment]
There's no public benchmarks, but includes documentation for the reward function: https://www.pettingzoo.ml/sisl/pursuit
