### ISSUE TITLE
Cannot Import from MAgent

### ISSUE THREAD

**Issue by amimem** [Farama-Foundation/PettingZoo#603]
I have been trying to import MAgent envs for several days without any success. I am particularly interested in the Battle environment.

- Python version: 3.8
- PettingZoo version: 1.14.0

How to reproduce the error(s):

- battle_v3

```python
from pettingzoo.magent import battle_v3 #or any other environment
```
Expected error:
`cannot import name 'battle_v3' from 'pettingzoo.magent'`

- battle_v2

```python
from pettingzoo.magent import battle_v2
print(battle_v2.env())
```
Expected error:
`pettingzoo.utils.deprecated_module.DeprecatedEnv: battle_v2 is now deprecated, use battle_v3 instead`

Also, installing dependencies using `pip install pettingzoo[all]` or `pip install pettingzoo[magent]` is not possible and raises the following error:
`zsh: no matches found: pettingzoo[magent]`.

I need to run some experiments on these environments ASAP, is there any work-around ?

**Comment by benblack769** [comment]
For the import issue, this is a known issue that we have been looking into, but have not been able to track down yet.

We have had success working around the problem by doing:

```
import pettingzoo.magent.battle_v3 as battle_v3
```

For the installation issue with `pip install pettingzoo[all]` or `pip install pettingzoo[magent]`, I was unable to reproduce it on my machine with pettingzoo==1.14.0 and python==3.8. However, I will note that if you tried to install the original geekai magent repository manually rather than the FaramaFoundation's fork (this is the one that installs with `pip install magent` you might have problems with the installation, and I would advise you create a new, clean virtualenvironment to work off of.

**Comment by amimem** [comment]
Thanks for the swift reply @benblack769. The issue with installing dependencies was that my shell (zsh) uses brackets for pattern matching so I had to use `pip install 'pettingzoo[magent]'` to install them. Also, this seemed to solve the import error, could you confirm that the dependencies are the root cause of the import errors and probably update the docs to include this important step before using MAgent envs ?

**Comment by jkterry1** [comment]
@benblack769 for your reference, zsh (which requires the qoutes for installation here) is what all macs have now. Apple dropped bash over gplv3 disputes
