### ISSUE TITLE
Atari Game: Pong stucks at the beginning

### ISSUE THREAD

**Issue by andysu2008** [Farama-Foundation/PettingZoo#621]
Ok. If I do `pong_v2`.
and I make the following actions (player 1 moves at 8).
`env.step(8, <player2_action>)`.

This will make the game stuck (pong doesn't repawn). 

Any help to get unstuck? This "stuck" behavior induces +200 or even +300 rewards which breaks up my RL training. Any help or quick fix to force the game to get unstuck?

**Comment by benblack769** [comment]
So the basic problem is that one player has to server the ball for the game to start. The idea is that the player who need to serve is penalized if the serve doesn't happen for 2 game seconds. Relevant code here https://github.com/Farama-Foundation/Multi-Agent-ALE/blob/master/src/games/supported/Pong.cpp#L45

So player 1, the one who is failing to serve, should be getting something like -200 reward over an episode, and player 2 should be getting +200 reward. Is this what is occuring? If not, then there is a bug in the above code.

**Comment by benblack769** [comment]
So I reproduced the issue locally, and what I described is indeed what seems to be occuring. The agent which has a constant action (preventing it from serving) gets negative reward (because it isn't serving). This is intentional behavior, meant to encourage it to serve. While I have seen this behavior before, I belive it is simply caused by normal RL learning instability. I would play around with the learning hyperparameters and see if the issue remains.
