### ISSUE TITLE
Can't use num_agents of Parallel API

### ISSUE THREAD

**Issue by dwyzzy** [Farama-Foundation/PettingZoo#640]
I can't get num_agents of the environment when using env.num_agents.
The problem can be reproduced using the code
`from pettingzoo.mpe import simple_speaker_listener_v3`
`env = simple_speaker_listener_v3.parallel_env()`
`print(env.num_agents)`

And the exception is
`AttributeError: 'aec_to_parallel_wrapper' object has no attribute 'agents'`

**Comment by benblack769** [comment]
We support variable numbers of agents in an environment. Due to that, you will have to do a reset() before using `env.num_agents`.

If you need to get the number of agents before reset(), then 

```
from pettingzoo.mpe import simple_speaker_listener_v3
env = simple_speaker_listener_v3.parallel_env()
print(env.max_num_agents)
```

Not all environments are guarenteed to support this (as some environments, like neural MMO, have no fixed number), but all environments currently in pettingzoo do.

**Comment by dwyzzy** [comment]
> We support variable numbers of agents in an environment. Due to that, you will have to do a reset() before using `env.num_agents`.
> 
> If you need to get the number of agents before reset(), then
> 
> ```
> from pettingzoo.mpe import simple_speaker_listener_v3
> env = simple_speaker_listener_v3.parallel_env()
> print(env.max_num_agents)
> ```
> 
> Not all environments are guarenteed to support this (as some environments, like neural MMO, have no fixed number), but all environments currently in pettingzoo do.

Thank you very much!
