### ISSUE TITLE
TypeError: aec_to_parallel_wrapper.render() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by wagh311** [Farama-Foundation/PettingZoo#896]
### Question

I am learning Maddpg algorithm recently. After my algorithm is completed in the MPE environment training in Pettingzoo, I encountered the following problems when evaluating the algorithm：
`Traceback (most recent call last):
  File "D:\PyCharm 2021.2.2\code\maddpg-pettingzoo-pytorch-master\evaluate.py", line 41, in <module>
    frame_list.append(Image.fromarray(env.render(mode='rgb_array')))
TypeError: aec_to_parallel_wrapper.render() got an unexpected keyword argument 'mode'`
How can I solve this problem?

**Comment by elliottower** [comment]
In the current gymnasium and pettingzoo APIs `render_mode` is specified when you initialize the environment, rather than when you call `render()`, so that's why you're getting that error. If you remove `mode` it should work, then you can specify `render_mode` when initializing (e.g., `env = connect_four_v3.env(render_mode="human")`)

**Comment by wagh311** [comment]
> In the current gymnasium and pettingzoo APIs `render_mode` is specified when you initialize the environment, rather than when you call `render()`, so that's why you're getting that error. If you remove `mode` it should work, then you can specify `render_mode` when initializing (e.g., `env = connect_four_v3.env(render_mode="human")`)

Thank you very much for your answer, I will give it a try！
